<?php

use Magento\Framework\View\Element\Template;
use AccelaSearch\Search\ViewModel\ConfigHelper;
use AccelaSearch\Search\ViewModel\UserHelper;

/** @var Template $block */
/** @var ConfigHelper $configHelper */
/** @var UserHelper $userHelper */

$configHelper = $block->getConfigHelper();
$userHelper = $block->getUserHelper();
$configurationUrl = $configHelper->getConfigurationUrl();
$asConfig = [];
if ($configHelper->isPublishedVisitorType()) {
    $asConfig["visitorType"] = $userHelper->getCustomerGroup();
}
if ($configHelper->isPublishedCurrencyCode()) {
    $asConfig["currencyCode"] = $userHelper->getCurrencyCode();
}
?>
<?php if ($configurationUrl): ?>
<script
  src="https://layer.accelasearch.io/V2/loader.js"
  data-config="<?= $block->escapeHtmlAttr($configurationUrl) ?>"
></script>
<?php endif; ?>

<?php if ($userHelper->isLoggedIn()): ?>
    <script>
        window.AS_ADVANCED_CONFIG = <?= json_encode($asConfig) ?>
    </script>
<?php endif; ?>
